#include "graphics.h"
#include "gba.h"
#include "logic.h"
#include <stdio.h>

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

void drawCharacter(Character character, int clear) {
    if (clear) {
        drawRectDMA(character.x, character.y, character.size, character.size, BLACK);
    } else {
        drawImageDMA(character.x, character.y, character.size, character.size, character.image);
    }
}

void drawNum(int x, int y, int score, u16 color) {
    char str[3];
    sprintf(str, "%d", score);
    drawString(x, y, str, color);
}

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(BLACK);
    drawAppState(state);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    drawCharacter(state->player, 1);
    drawCharacter(state->enemy, 1);
    drawNum(10, 20, state->score, BLACK);
    drawNum(10, 10, state->time, BLACK);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    drawCharacter(state->player, 0);
    drawCharacter(state->enemy, 0);
    drawNum(10, 20, state->score, WHITE);
    drawNum(10, 10, state->time, WHITE);
}
